import QtQuick 2.15

ListModel {
    id: datasources

    // Core dashboard channels used across templates/widgets.
    ListElement {
        titlename: "RPM"
        defaultsymbol: "rpm"
        sourcename: "rpm"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "10000"
        stepsize: "1000"
        divisor: "1000"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "Speed"
        defaultsymbol: "kph"
        sourcename: "speed"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "320"
        stepsize: "40"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "Gear"
        defaultsymbol: ""
        sourcename: "Gear"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "8"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "MAP"
        defaultsymbol: "kPa"
        sourcename: "MAP"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "300"
        stepsize: "100"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "ECT"
        defaultsymbol: "°C"
        sourcename: "Watertemp"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "120"
        stepsize: "20"
        divisor: "1"
        supportedECUs: "Extender"
    }

    // Extender board analog raw channels.
    ListElement {
        titlename: "EX Analog Input 0"
        defaultsymbol: "V"
        sourcename: "EXAnalogInput0"
        supportedECU: ""
        decimalpoints: "3"
        decimalpoints2: "3"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Input 1"
        defaultsymbol: "V"
        sourcename: "EXAnalogInput1"
        supportedECU: ""
        decimalpoints: "3"
        decimalpoints2: "3"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Input 2"
        defaultsymbol: "V"
        sourcename: "EXAnalogInput2"
        supportedECU: ""
        decimalpoints: "3"
        decimalpoints2: "3"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Input 3"
        defaultsymbol: "V"
        sourcename: "EXAnalogInput3"
        supportedECU: ""
        decimalpoints: "3"
        decimalpoints2: "3"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Input 4"
        defaultsymbol: "V"
        sourcename: "EXAnalogInput4"
        supportedECU: ""
        decimalpoints: "3"
        decimalpoints2: "3"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Input 5"
        defaultsymbol: "V"
        sourcename: "EXAnalogInput5"
        supportedECU: ""
        decimalpoints: "3"
        decimalpoints2: "3"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Input 6"
        defaultsymbol: "V"
        sourcename: "EXAnalogInput6"
        supportedECU: ""
        decimalpoints: "3"
        decimalpoints2: "3"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Input 7"
        defaultsymbol: "V"
        sourcename: "EXAnalogInput7"
        supportedECU: ""
        decimalpoints: "3"
        decimalpoints2: "3"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }

    // Extender board calibrated analog channels.
    ListElement {
        titlename: "EX Analog Calc 0"
        defaultsymbol: ""
        sourcename: "EXAnalogCalc0"
        supportedECU: ""
        decimalpoints: "2"
        decimalpoints2: "2"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Calc 1"
        defaultsymbol: ""
        sourcename: "EXAnalogCalc1"
        supportedECU: ""
        decimalpoints: "2"
        decimalpoints2: "2"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Calc 2"
        defaultsymbol: ""
        sourcename: "EXAnalogCalc2"
        supportedECU: ""
        decimalpoints: "2"
        decimalpoints2: "2"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Calc 3"
        defaultsymbol: ""
        sourcename: "EXAnalogCalc3"
        supportedECU: ""
        decimalpoints: "2"
        decimalpoints2: "2"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Calc 4"
        defaultsymbol: ""
        sourcename: "EXAnalogCalc4"
        supportedECU: ""
        decimalpoints: "2"
        decimalpoints2: "2"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Calc 5"
        defaultsymbol: ""
        sourcename: "EXAnalogCalc5"
        supportedECU: ""
        decimalpoints: "2"
        decimalpoints2: "2"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Calc 6"
        defaultsymbol: ""
        sourcename: "EXAnalogCalc6"
        supportedECU: ""
        decimalpoints: "2"
        decimalpoints2: "2"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Analog Calc 7"
        defaultsymbol: ""
        sourcename: "EXAnalogCalc7"
        supportedECU: ""
        decimalpoints: "2"
        decimalpoints2: "2"
        maxvalue: "300"
        stepsize: "10"
        divisor: "1"
        supportedECUs: "Extender"
    }

    // Extender board digital channels.
    ListElement {
        titlename: "EX Digital Input 1"
        defaultsymbol: ""
        sourcename: "EXDigitalInput1"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "1"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Digital Input 2"
        defaultsymbol: ""
        sourcename: "EXDigitalInput2"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "1"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Digital Input 3"
        defaultsymbol: ""
        sourcename: "EXDigitalInput3"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "1"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Digital Input 4"
        defaultsymbol: ""
        sourcename: "EXDigitalInput4"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "1"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Digital Input 5"
        defaultsymbol: ""
        sourcename: "EXDigitalInput5"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "1"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Digital Input 6"
        defaultsymbol: ""
        sourcename: "EXDigitalInput6"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "1"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Digital Input 7"
        defaultsymbol: ""
        sourcename: "EXDigitalInput7"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "1"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
    ListElement {
        titlename: "EX Digital Input 8"
        defaultsymbol: ""
        sourcename: "EXDigitalInput8"
        supportedECU: ""
        decimalpoints: "0"
        decimalpoints2: "0"
        maxvalue: "1"
        stepsize: "1"
        divisor: "1"
        supportedECUs: "Extender"
    }
}
