name: Test build
on: [pull_request]
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.8.3'
          host: 'linux'
          target: 'desktop'
      - uses: actions/checkout@v4
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build --parallel
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "build/PowerTuneQMLGui"
